############### BD EN LA NUBE (NEON) ###############

spring.application.name=Web-de-Ventas-de-Computadoras

spring.datasource.url=jdbc:postgresql://ep-broad-lake-actij4sj-pooler.sa-east-1.aws.neon.tech/SmartZone?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Zme3XvCKzB7L
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

jwt.secret=vD3y8hQp9kZ4s2aF6t7E1nM0bXc4R8uP
jwt.expiration=3600000
jwt.refresh.expiration=604800000



############### BD LOCAL ###############
#spring.application.name=Web-de-Ventas-de-Computadoras
#spring.datasource.url=jdbc:postgresql://localhost:5432/WebSmartZone
#spring.datasource.username=postgres
#spring.datasource.password=admin
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.jdbc.time_zone=UTC
#spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.suffix=.html



############### MERCADOPAGO ###############
mercadopago.public.key=APP_USR-af44a021-2e4f-4b34-a007-5168a4cde9fe
mercadopago.access.token=APP_USR-3822900872052192-110518-bb0386980d403b254e0b905fd17b9fc7-2970216696


############### GOOGLE LOGIN ###############
spring.security.oauth2.client.registration.google.client-id=426940369688-klp7i8rrcdvvdugu3jgl4cs1k2crnnno.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.google.client-name=Google


############### FACEBOOK LOGIN ###############
spring.security.oauth2.client.registration.facebook.client-id=1226678929511191
spring.security.oauth2.client.registration.facebook.client-secret=5eb43f598d34463021a230fb5d16dd2c
spring.security.oauth2.client.registration.facebook.scope=email,public_profile
spring.security.oauth2.client.registration.facebook.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.facebook.client-name=Facebook

spring.security.oauth2.client.provider.facebook.authorization-uri=https://www.facebook.com/v12.0/dialog/oauth
spring.security.oauth2.client.provider.facebook.token-uri=https://graph.facebook.com/v12.0/oauth/access_token
spring.security.oauth2.client.provider.facebook.user-info-uri=https://graph.facebook.com/me?fields=id,name,email,picture
spring.security.oauth2.client.provider.facebook.user-name-attribute=id
