spring.application.name=Web-de-Ventas-de-Computadoras

spring.datasource.url=jdbc:postgresql://localhost:5432/WebSmartZone
spring.datasource.name=admin
spring.datasource.password=123456
spring.datasource.driver-class-name= org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.jdbc.time_zone=UTC